export enum BuyPageType {
    RESERVATION_NORMAL = "RESERVATION_NORMAL",
    SHOPPING_MALL = "SHOPPING_MALL",
    TIME_MALL = "TIME_MALL",
}

export enum CreateSalesTime {
    BEFORE_USE_END = "BEFORE_USE_END",
    BEFORE_USE_START = "BEFORE_USE_START",
    ONE_DAY_BEFORE = "ONE_DAY_BEFORE",
    N_HOURS_BEFORE = "N_HOURS_BEFORE",
    CUSTOM_TIME = "CUSTOM_TIME",
}
export enum BoardKeys  {
    QNA = "qna"
}