export enum BuyPageType {
    RESERVATION_NORMAL = "RESERVATION_NORMAL",
}

export enum CreateSalesTime {
    BEFORE_USE_END = "BEFORE_USE_END",
    BEFORE_USE_START = "BEFORE_USE_START",
    ONE_DAY_BEFORE = "ONE_DAY_BEFORE",
    N_HOURS_BEFORE = "N_HOURS_BEFORE",
    CUSTOM_TIME = "CUSTOM_TIME",
}